#!/usr/bin/env node
/**
 * Minimal slock CLI used by managed Claude Code runtimes.
 *
 * It talks only to the local daemon proxy. The wrapper generated by the daemon
 * supplies SLOCK_AGENT_PROXY_URL and SLOCK_AGENT_PROXY_TOKEN_FILE.
 */

import { readFileSync } from 'fs';
import { stdin, stdout, stderr, env, exit } from 'process';
import { fileURLToPath } from 'url';

interface CliRequest {
  method: string;
  path: string;
  body?: unknown;
}

function printUsage(): never {
  stderr.write(JSON.stringify({
    ok: false,
    code: 'USAGE',
    message: 'Usage: slock message check|send|read|search, slock channel members, slock server info, slock task list, slock profile get, slock integration list, slock reminder list',
  }) + '\n');
  exit(2);
}

function requireEnv(source: NodeJS.ProcessEnv, name: string): string {
  const value = source[name];
  if (!value) {
    throw Object.assign(new Error(`Missing ${name}`), { code: `MISSING_${name}` });
  }
  return value;
}

function readProxyToken(source: NodeJS.ProcessEnv): string {
  const tokenFile = requireEnv(source, 'SLOCK_AGENT_PROXY_TOKEN_FILE');
  try {
    return readFileSync(tokenFile, 'utf-8').trim();
  } catch (err) {
    throw Object.assign(new Error(`Failed to read proxy token file: ${(err as Error).message}`), {
      code: 'TOKEN_READ_FAILED',
    });
  }
}

async function readStdinText(): Promise<string> {
  if (stdin.isTTY) return '';
  const chunks: Buffer[] = [];
  for await (const chunk of stdin) {
    chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
  }
  return Buffer.concat(chunks).toString('utf-8').trim();
}

function getOption(args: string[], name: string): string | undefined {
  const index = args.indexOf(name);
  if (index < 0) return undefined;
  return args[index + 1];
}

function positionalArgs(args: string[]): string[] {
  const positions: string[] = [];
  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];
    if (arg.startsWith('-')) {
      i += 1;
      continue;
    }
    positions.push(arg);
  }
  return positions;
}

async function parseRequest(args: string[], source: NodeJS.ProcessEnv): Promise<CliRequest> {
  const [group, command, ...rest] = args;
  const agentId = requireEnv(source, 'SLOCK_AGENT_ID');
  const agentPrefix = `/internal/agent/${encodeURIComponent(agentId)}`;

  if (group === 'message' && command === 'check') {
    const limit = getOption(rest, '--limit');
    const query = new URLSearchParams();
    if (limit) query.set('limit', limit);
    const suffix = query.toString();
    return { method: 'GET', path: `${agentPrefix}/receive${suffix ? `?${suffix}` : ''}` };
  }

  if (group === 'message' && command === 'send') {
    const target = getOption(rest, '--target') ?? getOption(rest, '-t');
    if (!target) throw Object.assign(new Error('Missing --target'), { code: 'MISSING_TARGET' });
    const inline = positionalArgs(rest).join(' ').trim();
    const content = inline || await readStdinText();
    if (!content) throw Object.assign(new Error('Missing message content'), { code: 'MISSING_CONTENT' });
    return { method: 'POST', path: `${agentPrefix}/send`, body: { target, content } };
  }

  if (group === 'message' && command === 'read') {
    const channel = getOption(rest, '--channel') ?? getOption(rest, '--target') ?? getOption(rest, '-c');
    const limit = getOption(rest, '--limit');
    const query = new URLSearchParams();
    if (channel) query.set('channel', channel);
    if (limit) query.set('limit', limit);
    return { method: 'GET', path: `${agentPrefix}/history?${query}` };
  }

  if (group === 'message' && command === 'search') {
    const q = getOption(rest, '--query') ?? getOption(rest, '-q') ?? positionalArgs(rest).join(' ').trim();
    if (!q) throw Object.assign(new Error('Missing --query'), { code: 'MISSING_QUERY' });
    const channel = getOption(rest, '--channel') ?? getOption(rest, '--target') ?? getOption(rest, '-c');
    const limit = getOption(rest, '--limit');
    const query = new URLSearchParams();
    query.set('q', q);
    if (channel) query.set('channel', channel);
    if (limit) query.set('limit', limit);
    return { method: 'GET', path: `${agentPrefix}/search?${query}` };
  }

  if (group === 'channel' && command === 'members') {
    const channel = getOption(rest, '--channel') ?? getOption(rest, '--target') ?? getOption(rest, '-c');
    if (!channel) throw Object.assign(new Error('Missing --channel'), { code: 'MISSING_CHANNEL' });
    const query = new URLSearchParams();
    query.set('channel', channel);
    return { method: 'GET', path: `${agentPrefix}/channel-members?${query}` };
  }

  if (group === 'server' && command === 'info') {
    return { method: 'GET', path: `${agentPrefix}/server` };
  }

  if (group === 'task' && command === 'list') {
    const channel = getOption(rest, '--channel');
    const query = new URLSearchParams();
    if (channel) query.set('channel', channel);
    const suffix = query.toString();
    return { method: 'GET', path: `${agentPrefix}/tasks${suffix ? `?${suffix}` : ''}` };
  }

  if (group === 'profile' && command === 'get') {
    const handle = getOption(rest, '--handle') ?? getOption(rest, '-h') ?? positionalArgs(rest)[0];
    return { method: 'GET', path: `${agentPrefix}/profile${handle ? `/${encodeURIComponent(handle)}` : ''}` };
  }

  if (group === 'integration' && command === 'list') {
    return { method: 'GET', path: `${agentPrefix}/integrations` };
  }

  if (group === 'reminder' && command === 'list') {
    return { method: 'GET', path: `${agentPrefix}/reminders` };
  }

  printUsage();
}

export async function runSlockCli(argv: string[], io: {
  stdout?: Pick<typeof stdout, 'write'>;
  stderr?: Pick<typeof stderr, 'write'>;
  env?: NodeJS.ProcessEnv;
} = {}): Promise<number> {
  const out = io.stdout ?? stdout;
  const err = io.stderr ?? stderr;
  const cliEnv = io.env ?? env;
  try {
    const proxyUrl = requireEnv(cliEnv, 'SLOCK_AGENT_PROXY_URL');
    const token = readProxyToken(cliEnv);
    const request = await parseRequest(argv, cliEnv);
    const response = await fetch(new URL(request.path, proxyUrl), {
      method: request.method,
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
        'X-Agent-Id': requireEnv(cliEnv, 'SLOCK_AGENT_ID'),
      },
      body: request.body === undefined ? undefined : JSON.stringify(request.body),
    });

    const text = await response.text();
    if (!response.ok) {
      err.write(text || JSON.stringify({ ok: false, code: `HTTP_${response.status}` }) + '\n');
      return 1;
    }
    out.write(text.endsWith('\n') ? text : `${text}\n`);
    return 0;
  } catch (err) {
    const e = err as Error & { code?: string };
    (io.stderr ?? stderr).write(JSON.stringify({
      ok: false,
      code: e.code ?? 'CLI_FAILED',
      message: e.message,
    }) + '\n');
    return 1;
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  runSlockCli(process.argv.slice(2)).then((code) => {
    if (code !== 0) exit(code);
  });
}
