#!/usr/bin/env node
/**
 * Agent-facing slock CLI entry point.
 *
 * MVP commands (message check/read/send, memory read) are handled by the
 * new commander-based infrastructure in cli/ with canonical output.
 * All other commands delegate to the legacy parseRequest handler for
 * backward compatibility.
 *
 * The wrapper generated by the daemon supplies SLOCK_AGENT_PROXY_URL
 * and SLOCK_AGENT_PROXY_TOKEN_FILE.
 */

export { runSlockCli } from './cli/index.js';

import { runSlockCli } from './cli/index.js';
import { fileURLToPath } from 'url';
import { exit } from 'process';

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  runSlockCli(process.argv.slice(2)).then((code) => {
    if (code !== 0) exit(code);
  });
}
