#!/usr/bin/env node
/**
 * Minimal slock CLI used by managed Claude Code runtimes.
 *
 * It talks only to the local daemon proxy. The wrapper generated by the daemon
 * supplies SLOCK_AGENT_PROXY_URL and SLOCK_AGENT_PROXY_TOKEN_FILE.
 */

import { basename } from 'path';
import { existsSync, readFileSync, statSync, writeFileSync } from 'fs';
import { stdin, stdout, stderr, env, exit } from 'process';
import { fileURLToPath } from 'url';

interface CliRequest {
  method: string;
  path: string;
  body?: unknown;
  safety?: SafetyCheck;
  multipartUpload?: {
    filePath: string;
    channelTarget?: string;
    fieldName: string;
    mimeType?: string;
  };
  rawOutputFile?: string;
}

function printUsage(): never {
  stderr.write(JSON.stringify({
    ok: false,
    code: 'USAGE',
    message: 'Usage: slock message check|send|read|search|resolve|react, slock channel members|join|leave, slock thread read|summary|unfollow, slock server info, slock task list|claim|unclaim|update|create, slock profile show|get|update, slock integration list|login, slock reminder list|schedule|create|snooze|update|cancel|delete|log, slock attachment view|download|upload',
  }) + '\n');
  exit(2);
}

function requireEnv(source: NodeJS.ProcessEnv, name: string): string {
  const value = source[name];
  if (!value) {
    throw Object.assign(new Error(`Missing ${name}`), { code: `MISSING_${name}` });
  }
  return value;
}

function readProxyToken(source: NodeJS.ProcessEnv): string {
  const tokenFile = requireEnv(source, 'SLOCK_AGENT_PROXY_TOKEN_FILE');
  try {
    return readFileSync(tokenFile, 'utf-8').trim();
  } catch (err) {
    throw Object.assign(new Error(`Failed to read proxy token file: ${(err as Error).message}`), {
      code: 'TOKEN_READ_FAILED',
    });
  }
}

async function readStdinText(): Promise<string> {
  if (stdin.isTTY) return '';
  const chunks: Buffer[] = [];
  for await (const chunk of stdin) {
    chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(chunk));
  }
  return Buffer.concat(chunks).toString('utf-8').trim();
}

function getOption(args: string[], name: string): string | undefined {
  const index = args.indexOf(name);
  if (index < 0) return undefined;
  return args[index + 1];
}

function getOptions(args: string[], name: string): string[] {
  const values: string[] = [];
  for (let i = 0; i < args.length; i += 1) {
    if (args[i] === name && args[i + 1] !== undefined) {
      values.push(args[i + 1]);
      i += 1;
    }
  }
  return values;
}

function hasFlag(args: string[], name: string): boolean {
  return args.includes(name);
}

function positionalArgs(args: string[]): string[] {
  const positions: string[] = [];
  for (let i = 0; i < args.length; i += 1) {
    const arg = args[i];
    if (arg.startsWith('-')) {
      i += 1;
      continue;
    }
    positions.push(arg);
  }
  return positions;
}

function parseJsonOption(args: string[], name: string): unknown | undefined {
  const value = getOption(args, name);
  if (!value) return undefined;
  try {
    return JSON.parse(value);
  } catch (err) {
    throw Object.assign(new Error(`Invalid ${name} JSON: ${(err as Error).message}`), {
      code: 'INVALID_JSON',
    });
  }
}

function maybeNumber(value: string | undefined): number | undefined {
  if (value === undefined) return undefined;
  const num = Number(value);
  if (!Number.isFinite(num)) {
    throw Object.assign(new Error(`Expected numeric value, got ${value}`), {
      code: 'INVALID_NUMBER',
    });
  }
  return num;
}

function compactBody(values: Record<string, unknown>): Record<string, unknown> {
  return Object.fromEntries(Object.entries(values).filter(([, value]) => value !== undefined));
}

function requirePositiveInteger(raw: string, name: string): number {
  const value = Number(raw);
  if (!Number.isFinite(value) || !Number.isInteger(value) || value <= 0) {
    throw Object.assign(new Error(`${name} must be a positive integer; got ${raw}`), {
      code: 'INVALID_NUMBER',
    });
  }
  return value;
}

function inferMimeType(filename: string, buffer: Buffer, explicit?: string): string {
  if (explicit) return explicit;
  if (buffer.length >= 8 && buffer.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10]))) {
    return 'image/png';
  }
  if (buffer.length >= 3 && buffer.subarray(0, 3).equals(Buffer.from([255, 216, 255]))) {
    return 'image/jpeg';
  }
  const lower = filename.toLowerCase();
  if (lower.endsWith('.gif')) return 'image/gif';
  if (lower.endsWith('.webp')) return 'image/webp';
  if (lower.endsWith('.pdf')) return 'application/pdf';
  if (lower.endsWith('.md')) return 'text/markdown';
  if (lower.endsWith('.txt')) return 'text/plain';
  if (lower.endsWith('.json')) return 'application/json';
  if (lower.endsWith('.csv')) return 'text/csv';
  return 'application/octet-stream';
}

interface SafetyCheck {
  kind: 'write';
  resources: string[];
  warnings?: string[];
}

function writeSafety(...resources: Array<string | undefined>): SafetyCheck {
  return { kind: 'write', resources: resources.filter((value): value is string => !!value) };
}

function assertWriteAllowed(request: CliRequest, source: NodeJS.ProcessEnv): void {
  if (!request.safety) return;

  if (source.SLOCK_ALLOW_WRITES !== '1' && source.AAA_DAEMON_ALLOW_WRITES !== '1') {
    throw Object.assign(new Error('Write-capable slock commands require SLOCK_ALLOW_WRITES=1'), {
      code: 'WRITES_NOT_ALLOWED',
    });
  }

  const allowlist = source.SLOCK_WRITE_TARGET_ALLOWLIST ?? source.AAA_DAEMON_WRITE_TARGET_ALLOWLIST;
  if (!allowlist) return;

  const allowed = allowlist.split(',').map((item) => item.trim()).filter(Boolean);
  if (allowed.length === 0) return;

  const denied = request.safety.resources.filter((resource) => (
    !allowed.some((entry) => resource === entry || resource.startsWith(entry))
  ));
  if (denied.length > 0) {
    throw Object.assign(new Error(`Write target is not allowlisted: ${denied.join(', ')}`), {
      code: 'WRITE_TARGET_NOT_ALLOWED',
    });
  }
}

function dmTargetHint(target: string): string | undefined {
  if (target === 'dm:@deepseek') {
    return 'Hint: in the verified DeepSeek DM, the CLI runs as the DeepSeek agent. Use the human peer target dm:@zy-ean, not dm:@deepseek.';
  }
  return undefined;
}

function enrichProxyFailure(text: string, status: number): string {
  const lower = text.toLowerCase();
  if (lower.includes('machine api key required') || lower.includes('machine api key')) {
    const suffix = text.endsWith('\n') ? '' : '\n';
    return `${text}${suffix}${JSON.stringify({
      ok: false,
      code: 'MACHINE_API_KEY_REQUIRED_HINT',
      hint: 'Real aaa-daemon/Slock tests should import a local Slock runtime and route through this project AgentProxy; do not point the test CLI directly at the official/running daemon proxy.',
    })}\n`;
  }
  if (!text) return JSON.stringify({ ok: false, code: `HTTP_${status}` }) + '\n';
  return text;
}

async function parseRequest(args: string[], source: NodeJS.ProcessEnv): Promise<CliRequest> {
  const [group, command, ...rest] = args;
  const agentId = requireEnv(source, 'SLOCK_AGENT_ID');
  const agentPrefix = `/internal/agent/${encodeURIComponent(agentId)}`;

  if (group === 'message' && command === 'check') {
    const limit = getOption(rest, '--limit');
    const query = new URLSearchParams();
    if (limit) query.set('limit', limit);
    const suffix = query.toString();
    return { method: 'GET', path: `${agentPrefix}/receive${suffix ? `?${suffix}` : ''}` };
  }

  if (group === 'message' && command === 'send') {
    const target = getOption(rest, '--target') ?? getOption(rest, '-t');
    if (!target) throw Object.assign(new Error('Missing --target'), { code: 'MISSING_TARGET' });
    const inline = positionalArgs(rest).join(' ').trim();
    const content = inline || await readStdinText();
    if (!content) throw Object.assign(new Error('Missing message content'), { code: 'MISSING_CONTENT' });
    const attachmentIds = getOptions(rest, '--attachment-id');
    const body = compactBody({
      target,
      content,
      attachmentIds: attachmentIds.length > 0 ? attachmentIds : undefined,
    });
    const request: CliRequest = { method: 'POST', path: `${agentPrefix}/send`, body, safety: writeSafety(target) };
    const hint = dmTargetHint(target);
    if (hint) {
      const safety = request.safety ?? writeSafety(target);
      request.safety = { kind: safety.kind, resources: safety.resources, warnings: [...(safety.warnings ?? []), hint] };
    }
    return request;
  }

  if (group === 'message' && command === 'react') {
    const messageId = getOption(rest, '--message-id') ?? getOption(rest, '--message') ?? getOption(rest, '-m') ?? positionalArgs(rest)[0];
    const reaction = getOption(rest, '--reaction') ?? getOption(rest, '--emoji') ?? getOption(rest, '-r') ?? positionalArgs(rest)[1];
    if (!messageId) throw Object.assign(new Error('Missing --message-id'), { code: 'MISSING_MESSAGE_ID' });
    if (!reaction) throw Object.assign(new Error('Missing --reaction'), { code: 'MISSING_REACTION' });
    const remove = hasFlag(rest, '--remove') || hasFlag(rest, '--delete');
    return {
      method: remove ? 'DELETE' : 'POST',
      path: `${agentPrefix}/messages/${encodeURIComponent(messageId)}/reactions`,
      body: remove ? { reaction } : { reaction },
      safety: writeSafety(messageId),
    };
  }

  if (group === 'message' && command === 'read') {
    const channel = getOption(rest, '--channel') ?? getOption(rest, '--target') ?? getOption(rest, '-c');
    const limit = getOption(rest, '--limit');
    const query = new URLSearchParams();
    if (channel) query.set('channel', channel);
    if (limit) query.set('limit', limit);
    return { method: 'GET', path: `${agentPrefix}/history?${query}` };
  }

  if (group === 'message' && command === 'search') {
    const q = getOption(rest, '--query') ?? getOption(rest, '-q') ?? positionalArgs(rest).join(' ').trim();
    if (!q) throw Object.assign(new Error('Missing --query'), { code: 'MISSING_QUERY' });
    const channel = getOption(rest, '--channel') ?? getOption(rest, '--target') ?? getOption(rest, '-c');
    const limit = getOption(rest, '--limit');
    const query = new URLSearchParams();
    query.set('q', q);
    if (channel) query.set('channel', channel);
    if (limit) query.set('limit', limit);
    return { method: 'GET', path: `${agentPrefix}/search?${query}` };
  }

  if (group === 'message' && command === 'resolve') {
    const messageId = getOption(rest, '--message-id') ?? getOption(rest, '--message') ?? getOption(rest, '--id') ?? getOption(rest, '-m') ?? positionalArgs(rest)[0];
    if (!messageId) throw Object.assign(new Error('Missing --message-id'), { code: 'MISSING_MESSAGE_ID' });
    return { method: 'GET', path: `${agentPrefix}/messages/${encodeURIComponent(messageId)}/resolve` };
  }

  if (group === 'channel' && command === 'members') {
    const channel = getOption(rest, '--channel') ?? getOption(rest, '--target') ?? getOption(rest, '-c');
    if (!channel) throw Object.assign(new Error('Missing --channel'), { code: 'MISSING_CHANNEL' });
    const query = new URLSearchParams();
    query.set('channel', channel);
    return { method: 'GET', path: `${agentPrefix}/channel-members?${query}` };
  }

  if (group === 'channel' && (command === 'join' || command === 'leave')) {
    const channel = getOption(rest, '--target') ?? getOption(rest, '--channel') ?? getOption(rest, '-c') ?? positionalArgs(rest)[0];
    if (!channel) throw Object.assign(new Error('Missing --channel'), { code: 'MISSING_CHANNEL' });
    const channelId = getOption(rest, '--channel-id');
    return {
      method: 'POST',
      path: `${agentPrefix}/channels/${encodeURIComponent(channelId ?? channel)}/${command}`,
      safety: writeSafety(channel),
    };
  }

  if (group === 'server' && command === 'info') {
    return { method: 'GET', path: `${agentPrefix}/server` };
  }

  if (group === 'thread' && command === 'read') {
    const threadId = getOption(rest, '--thread-id') ?? getOption(rest, '--id') ?? positionalArgs(rest)[0];
    if (!threadId) throw Object.assign(new Error('Missing --thread-id'), { code: 'MISSING_THREAD_ID' });
    return { method: 'GET', path: `${agentPrefix}/threads/${encodeURIComponent(threadId)}` };
  }

  if (group === 'thread' && command === 'summary') {
    const threadId = getOption(rest, '--thread-id') ?? getOption(rest, '--id') ?? positionalArgs(rest)[0];
    if (!threadId) throw Object.assign(new Error('Missing --thread-id'), { code: 'MISSING_THREAD_ID' });
    const inline = getOption(rest, '--summary') ?? getOption(rest, '--text') ?? positionalArgs(rest).slice(1).join(' ').trim();
    const summary = inline || await readStdinText();
    if (!summary) throw Object.assign(new Error('Missing --summary'), { code: 'MISSING_SUMMARY' });
    return {
      method: 'POST',
      path: `${agentPrefix}/threads/${encodeURIComponent(threadId)}/summary`,
      body: { summary },
      safety: writeSafety(`thread:${threadId}`),
    };
  }

  if (group === 'thread' && command === 'unfollow') {
    const threadId = getOption(rest, '--target') ?? getOption(rest, '--thread-id') ?? getOption(rest, '--id') ?? positionalArgs(rest)[0];
    if (!threadId) throw Object.assign(new Error('Missing --target or --thread-id'), { code: 'MISSING_THREAD_ID' });
    return {
      method: 'POST',
      path: `${agentPrefix}/threads/unfollow`,
      body: { threadId },
      safety: writeSafety(`thread:${threadId}`),
    };
  }

  if (group === 'task' && command === 'list') {
    const channel = getOption(rest, '--channel');
    const query = new URLSearchParams();
    if (channel) query.set('channel', channel);
    const status = getOption(rest, '--status');
    if (status) query.set('status', status);
    const suffix = query.toString();
    return { method: 'GET', path: `${agentPrefix}/tasks${suffix ? `?${suffix}` : ''}` };
  }

  if (group === 'task' && command === 'claim') {
    const channel = getOption(rest, '--channel');
    const numbers = getOptions(rest, '--number').map((raw) => requirePositiveInteger(raw, '--number'));
    const messageIds = getOptions(rest, '--message-id');
    if (channel && (numbers.length > 0 || messageIds.length > 0)) {
      return {
        method: 'POST',
        path: `${agentPrefix}/tasks/claim`,
        body: compactBody({
          channel,
          task_numbers: numbers.length > 0 ? numbers : undefined,
          message_ids: messageIds.length > 0 ? messageIds : undefined,
        }),
        safety: writeSafety(channel),
      };
    }

    const taskId = getOption(rest, '--id') ?? getOption(rest, '--task-id') ?? positionalArgs(rest)[0];
    const assignee = getOption(rest, '--assignee') ?? getOption(rest, '-a');
    if (!taskId) throw Object.assign(new Error('Missing --id or --channel with --number/--message-id'), { code: 'MISSING_TASK_ID' });
    return {
      method: 'POST',
      path: `${agentPrefix}/tasks/${encodeURIComponent(taskId)}/claim`,
      body: compactBody({ assignee }),
      safety: writeSafety(taskId),
    };
  }

  if (group === 'task' && command === 'unclaim') {
    const channel = getOption(rest, '--channel');
    const number = getOption(rest, '--number');
    if (channel && number && !getOption(rest, '--id') && !getOption(rest, '--task-id')) {
      return {
        method: 'POST',
        path: `${agentPrefix}/tasks/update-status`,
        body: { channel, task_number: requirePositiveInteger(number, '--number'), status: 'todo' },
        safety: writeSafety(channel),
      };
    }

    const taskId = getOption(rest, '--id') ?? getOption(rest, '--task-id') ?? positionalArgs(rest)[0];
    if (!taskId) throw Object.assign(new Error('Missing --id or --channel with --number'), { code: 'MISSING_TASK_ID' });
    return {
      method: 'POST',
      path: `${agentPrefix}/tasks/${encodeURIComponent(taskId)}/unclaim`,
      safety: writeSafety(taskId),
    };
  }

  if (group === 'task' && command === 'update') {
    const channel = getOption(rest, '--channel');
    const number = getOption(rest, '--number');
    const status = getOption(rest, '--status');
    if (channel && number && status && !getOption(rest, '--id') && !getOption(rest, '--task-id')) {
      return {
        method: 'POST',
        path: `${agentPrefix}/tasks/update-status`,
        body: { channel, task_number: requirePositiveInteger(number, '--number'), status },
        safety: writeSafety(channel),
      };
    }

    const taskId = getOption(rest, '--id') ?? getOption(rest, '--task-id') ?? positionalArgs(rest)[0];
    if (!taskId) throw Object.assign(new Error('Missing --id'), { code: 'MISSING_TASK_ID' });
    const title = getOption(rest, '--title');
    const assignee = getOption(rest, '--assignee') ?? getOption(rest, '-a');
    const body = compactBody({
      title,
      status,
      assignee,
      channel,
      data: parseJsonOption(rest, '--json'),
    });
    if (Object.keys(body).length === 0) throw Object.assign(new Error('Missing task update fields'), { code: 'MISSING_UPDATE_FIELDS' });
    return {
      method: 'PATCH',
      path: `${agentPrefix}/tasks/${encodeURIComponent(taskId)}`,
      body,
      safety: writeSafety(taskId, channel),
    };
  }

  if (group === 'task' && command === 'create') {
    const titles = getOptions(rest, '--title');
    const title = titles[0] ?? positionalArgs(rest).join(' ').trim();
    const channel = getOption(rest, '--channel');
    if (!title) throw Object.assign(new Error('Missing --title'), { code: 'MISSING_TITLE' });
    if (!channel) throw Object.assign(new Error('Missing --channel'), { code: 'MISSING_CHANNEL' });
    const body = titles.length > 0
      ? { channel, tasks: titles.map((item) => ({ title: item })) }
      : compactBody({
        title,
        channel,
        assignee: getOption(rest, '--assignee') ?? getOption(rest, '-a'),
        status: getOption(rest, '--status'),
        messageId: getOption(rest, '--message-id'),
        data: parseJsonOption(rest, '--json'),
      });
    return { method: 'POST', path: `${agentPrefix}/tasks`, body, safety: writeSafety(channel) };
  }

  if (group === 'profile' && (command === 'get' || command === 'show')) {
    const handle = getOption(rest, '--handle') ?? getOption(rest, '-h') ?? positionalArgs(rest)[0];
    return { method: 'GET', path: `${agentPrefix}/profile${handle ? `/${encodeURIComponent(handle)}` : ''}` };
  }

  if (group === 'profile' && command === 'update') {
    const avatarFile = getOption(rest, '--avatar-file');
    if (avatarFile) {
      return {
        method: 'POST',
        path: `${agentPrefix}/profile/avatar`,
        multipartUpload: {
          filePath: avatarFile,
          fieldName: 'avatar',
          mimeType: getOption(rest, '--mime-type') ?? getOption(rest, '--content-type'),
        },
        safety: writeSafety('profile'),
      };
    }

    const body = compactBody({
      displayName: getOption(rest, '--display-name'),
      description: getOption(rest, '--description') ?? getOption(rest, '--bio'),
      avatarUrl: getOption(rest, '--avatar-url'),
      status: getOption(rest, '--status'),
      data: parseJsonOption(rest, '--json'),
    });
    if (Object.keys(body).length === 0) throw Object.assign(new Error('Missing profile update fields'), { code: 'MISSING_UPDATE_FIELDS' });
    return { method: 'POST', path: `${agentPrefix}/profile`, body, safety: writeSafety('profile') };
  }

  if (group === 'integration' && command === 'list') {
    return { method: 'GET', path: `${agentPrefix}/integrations` };
  }

  if (group === 'integration' && command === 'login') {
    const service = getOption(rest, '--service') ?? getOption(rest, '--provider') ?? positionalArgs(rest)[0];
    if (!service) throw Object.assign(new Error('Missing --service'), { code: 'MISSING_PROVIDER' });
    const scopes = getOptions(rest, '--scope')
      .flatMap((value) => value.split(','))
      .map((value) => value.trim())
      .filter(Boolean);
    return {
      method: 'POST',
      path: `${agentPrefix}/integrations/login`,
      body: compactBody({
        service,
        scopes: scopes.length > 0 ? scopes : undefined,
        redirectUrl: getOption(rest, '--redirect-url'),
      }),
      safety: writeSafety(`integration:${service}`),
    };
  }

  if (group === 'reminder' && command === 'list') {
    return { method: 'GET', path: `${agentPrefix}/reminders` };
  }

  if (group === 'reminder' && (command === 'create' || command === 'schedule')) {
    const title = getOption(rest, '--title') ?? getOption(rest, '--text') ?? getOption(rest, '--message') ?? positionalArgs(rest).join(' ').trim();
    const at = getOption(rest, '--fire-at') ?? getOption(rest, '--at');
    const delaySeconds = getOption(rest, '--delay-seconds');
    const channel = getOption(rest, '--channel');
    const msgId = getOption(rest, '--msg-id');
    if (!title) throw Object.assign(new Error('Missing --title'), { code: 'MISSING_TEXT' });
    if (!at && !delaySeconds) throw Object.assign(new Error('Missing --fire-at or --delay-seconds'), { code: 'MISSING_AT' });
    return {
      method: 'POST',
      path: `${agentPrefix}/reminders`,
      body: compactBody({
        title,
        fireAt: at,
        delaySeconds: maybeNumber(delaySeconds),
        repeat: getOption(rest, '--repeat'),
        channel,
        msgId,
        data: parseJsonOption(rest, '--json'),
      }),
      safety: writeSafety(channel ?? 'reminder'),
    };
  }

  if (group === 'reminder' && command === 'update') {
    const reminderId = getOption(rest, '--id') ?? getOption(rest, '--reminder-id') ?? positionalArgs(rest)[0];
    if (!reminderId) throw Object.assign(new Error('Missing --id'), { code: 'MISSING_REMINDER_ID' });
    const body = compactBody({
      title: getOption(rest, '--title') ?? getOption(rest, '--text') ?? getOption(rest, '--message'),
      fireAt: getOption(rest, '--fire-at') ?? getOption(rest, '--at'),
      delaySeconds: maybeNumber(getOption(rest, '--in') ?? getOption(rest, '--delay-seconds')),
      repeat: getOption(rest, '--cadence') ?? getOption(rest, '--repeat'),
      channel: getOption(rest, '--channel'),
      done: hasFlag(rest, '--done') ? true : undefined,
      data: parseJsonOption(rest, '--json'),
    });
    if (Object.keys(body).length === 0) throw Object.assign(new Error('Missing reminder update fields'), { code: 'MISSING_UPDATE_FIELDS' });
    return {
      method: 'PATCH',
      path: `${agentPrefix}/reminders/${encodeURIComponent(reminderId)}`,
      body,
      safety: writeSafety(reminderId),
    };
  }

  if (group === 'reminder' && command === 'snooze') {
    const reminderId = getOption(rest, '--id') ?? getOption(rest, '--reminder-id') ?? positionalArgs(rest)[0];
    if (!reminderId) throw Object.assign(new Error('Missing --id'), { code: 'MISSING_REMINDER_ID' });
    const delaySeconds = getOption(rest, '--in') ?? getOption(rest, '--delay-seconds');
    const fireAt = getOption(rest, '--fire-at') ?? getOption(rest, '--at');
    if (!delaySeconds && !fireAt) {
      throw Object.assign(new Error('Missing --delay-seconds or --fire-at'), { code: 'MISSING_AT' });
    }
    return {
      method: 'PATCH',
      path: `${agentPrefix}/reminders/${encodeURIComponent(reminderId)}`,
      body: compactBody({
        delaySeconds: maybeNumber(delaySeconds),
        fireAt,
      }),
      safety: writeSafety(reminderId),
    };
  }

  if (group === 'reminder' && (command === 'delete' || command === 'remove' || command === 'cancel')) {
    const reminderId = getOption(rest, '--id') ?? getOption(rest, '--reminder-id') ?? positionalArgs(rest)[0];
    if (!reminderId) throw Object.assign(new Error('Missing --id'), { code: 'MISSING_REMINDER_ID' });
    return {
      method: 'DELETE',
      path: `${agentPrefix}/reminders/${encodeURIComponent(reminderId)}`,
      safety: writeSafety(reminderId),
    };
  }

  if (group === 'reminder' && command === 'log') {
    const reminderId = getOption(rest, '--id') ?? getOption(rest, '--reminder-id') ?? positionalArgs(rest)[0];
    if (!reminderId) throw Object.assign(new Error('Missing --id'), { code: 'MISSING_REMINDER_ID' });
    return { method: 'GET', path: `${agentPrefix}/reminders/${encodeURIComponent(reminderId)}/log` };
  }

  if (group === 'attachment' && (command === 'download' || command === 'view')) {
    const attachmentId = getOption(rest, '--id') ?? getOption(rest, '--attachment-id') ?? positionalArgs(rest)[0];
    if (!attachmentId) throw Object.assign(new Error('Missing --id'), { code: 'MISSING_ATTACHMENT_ID' });
    const output = getOption(rest, '--output');
    const suffix = command === 'download' ? '/download' : '';
    return { method: 'GET', path: `/api/attachments/${encodeURIComponent(attachmentId)}${suffix}`, rawOutputFile: output };
  }

  if (group === 'attachment' && command === 'upload') {
    const target = getOption(rest, '--channel') ?? getOption(rest, '--target') ?? getOption(rest, '-t');
    const path = getOption(rest, '--file') ?? getOption(rest, '--path') ?? positionalArgs(rest)[0];
    if (!target) throw Object.assign(new Error('Missing --target'), { code: 'MISSING_TARGET' });
    if (!path) throw Object.assign(new Error('Missing --file'), { code: 'MISSING_FILE' });
    return {
      method: 'POST',
      path: `${agentPrefix}/upload`,
      multipartUpload: {
        filePath: path,
        channelTarget: target,
        fieldName: 'file',
        mimeType: getOption(rest, '--mime-type') ?? getOption(rest, '--content-type'),
      },
      safety: writeSafety(target),
    };
  }

  printUsage();
}

export async function runSlockCli(argv: string[], io: {
  stdout?: Pick<typeof stdout, 'write'>;
  stderr?: Pick<typeof stderr, 'write'>;
  env?: NodeJS.ProcessEnv;
} = {}): Promise<number> {
  const out = io.stdout ?? stdout;
  const err = io.stderr ?? stderr;
  const cliEnv = io.env ?? env;
  try {
    const proxyUrl = requireEnv(cliEnv, 'SLOCK_AGENT_PROXY_URL');
    const token = readProxyToken(cliEnv);
    const request = await parseRequest(argv, cliEnv);
    assertWriteAllowed(request, cliEnv);

    if (request.multipartUpload) {
      const upload = request.multipartUpload;
      if (!existsSync(upload.filePath)) {
        throw Object.assign(new Error(`File does not exist: ${upload.filePath}`), { code: 'MISSING_FILE' });
      }
      const stat = statSync(upload.filePath);
      if (!stat.isFile()) {
        throw Object.assign(new Error(`Not a regular file: ${upload.filePath}`), { code: 'INVALID_FILE' });
      }
      if (stat.size <= 0) {
        throw Object.assign(new Error('Refusing to upload a 0-byte attachment'), { code: 'INVALID_FILE' });
      }

      const buffer = readFileSync(upload.filePath);
      const filename = basename(upload.filePath);
      const form = new FormData();
      form.append(upload.fieldName, new Blob([buffer], { type: inferMimeType(filename, buffer, upload.mimeType) }), filename);
      if (upload.channelTarget) {
        const resolved = await fetch(new URL(`/internal/agent/${encodeURIComponent(requireEnv(cliEnv, 'SLOCK_AGENT_ID'))}/resolve-channel`, proxyUrl), {
          method: 'POST',
          headers: {
            'Authorization': `Bearer ${token}`,
            'Content-Type': 'application/json',
            'X-Agent-Id': requireEnv(cliEnv, 'SLOCK_AGENT_ID'),
          },
          body: JSON.stringify({ target: upload.channelTarget }),
        });
        const resolvedText = await resolved.text();
        if (!resolved.ok) {
          err.write(enrichProxyFailure(resolvedText, resolved.status));
          return 1;
        }
        const channelId = (JSON.parse(resolvedText) as { channelId?: string }).channelId;
        if (!channelId) {
          throw Object.assign(new Error(`Could not resolve channel: ${upload.channelTarget}`), { code: 'RESOLVE_FAILED' });
        }
        form.append('channelId', channelId);
      }
      if (upload.mimeType) form.append('mimeType', upload.mimeType);
      const response = await fetch(new URL(request.path, proxyUrl), {
        method: request.method,
        headers: {
          'Authorization': `Bearer ${token}`,
          'X-Agent-Id': requireEnv(cliEnv, 'SLOCK_AGENT_ID'),
        },
        body: form,
      });
      const text = await response.text();
      if (!response.ok) {
        err.write(enrichProxyFailure(text, response.status));
        return 1;
      }
      out.write(text.endsWith('\n') ? text : `${text}\n`);
      return 0;
    }

    const response = await fetch(new URL(request.path, proxyUrl), {
      method: request.method,
      headers: {
        'Authorization': `Bearer ${token}`,
        'Content-Type': 'application/json',
        'X-Agent-Id': requireEnv(cliEnv, 'SLOCK_AGENT_ID'),
      },
      body: request.body === undefined ? undefined : JSON.stringify(request.body),
    });

    if (request.rawOutputFile && response.ok) {
      const buffer = Buffer.from(await response.arrayBuffer());
      writeFileSync(request.rawOutputFile, buffer);
      out.write(JSON.stringify({ ok: true, output: request.rawOutputFile }) + '\n');
      return 0;
    }

    const text = await response.text();
    if (!response.ok) {
      err.write(text || JSON.stringify({ ok: false, code: `HTTP_${response.status}` }) + '\n');
      return 1;
    }
    out.write(text.endsWith('\n') ? text : `${text}\n`);
    return 0;
  } catch (err) {
    const e = err as Error & { code?: string };
    (io.stderr ?? stderr).write(JSON.stringify({
      ok: false,
      code: e.code ?? 'CLI_FAILED',
      message: e.message,
    }) + '\n');
    return 1;
  }
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  runSlockCli(process.argv.slice(2)).then((code) => {
    if (code !== 0) exit(code);
  });
}
