"""baseline

Revision ID: 77b8b147f689
Revises:
Create Date: 2026-07-19 13:35:24.227020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '77b8b147f689'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # pgcrypto provides gen_random_uuid(); historically created by seed.py and
    # available in every existing environment. Created here so fresh installs match.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    op.create_table('servers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=True),
    sa.Column('resource_type', sa.String(length=20), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_api_keys_prefix', 'api_keys', ['key_prefix'], unique=False)
    op.create_table('computers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('machine_id', sa.String(length=80), nullable=True),
    sa.Column('os', sa.String(length=80), nullable=False),
    sa.Column('daemon_version', sa.String(length=80), nullable=False),
    sa.Column('api_key_prefix', sa.String(length=40), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('detected_runtimes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('active_daemon_id', sa.String(length=80), nullable=True),
    sa.Column('daemon_lease_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'name', name='uq_computers_server_name')
    )
    op.create_index('idx_computers_server', 'computers', ['server_id'], unique=False)
    op.create_index('idx_computers_server_machine', 'computers', ['server_id', 'machine_id'], unique=False)
    op.create_index('uq_computers_server_machine', 'computers', ['server_id', 'machine_id'], unique=True, postgresql_where=sa.text('machine_id IS NOT NULL'))
    op.create_table('connect_tickets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('requested_name', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_connect_tickets_prefix', 'connect_tickets', ['key_prefix'], unique=False)
    op.create_index('idx_connect_tickets_server', 'connect_tickets', ['server_id'], unique=False)
    op.create_table('external_connectors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('secret_ref', sa.Text(), nullable=True),
    sa.Column('encrypted_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_error_code', sa.String(length=80), nullable=True),
    sa.Column('last_error_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'disabled', 'error')", name='ck_external_connectors_status'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_external_connectors_server_provider', 'external_connectors', ['server_id', 'provider', 'status'], unique=False)
    op.create_table('external_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('local_type', sa.String(length=40), nullable=False),
    sa.Column('local_id', sa.UUID(), nullable=False),
    sa.Column('external_type', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.Text(), nullable=False),
    sa.Column('external_url', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['external_connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_external_mappings_external', 'external_mappings', ['connector_id', 'external_type', 'external_id'], unique=False)
    op.create_index('idx_external_mappings_local', 'external_mappings', ['server_id', 'local_type', 'local_id'], unique=False)
    op.create_index('uq_external_mappings_pair', 'external_mappings', ['connector_id', 'local_type', 'local_id', 'external_type', 'external_id'], unique=True)
    op.create_table('members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('computer_id', sa.UUID(), nullable=True),
    sa.Column('backend', sa.String(length=40), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['computer_id'], ['computers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'display_name', name='uq_members_server_display_name')
    )
    op.create_index('idx_members_computer', 'members', ['computer_id'], unique=False)
    op.create_index('idx_members_server', 'members', ['server_id'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('session_token_hash', sa.String(length=64), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_accounts_name')
    )
    op.create_index('idx_accounts_member', 'accounts', ['member_id'], unique=False)
    op.create_table('agent_workspaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('computer_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('runtime', sa.String(length=40), nullable=False),
    sa.Column('runtime_command', sa.Text(), nullable=True),
    sa.Column('runtime_model', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('cwd', sa.Text(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['computer_id'], ['computers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_workspaces_agent', 'agent_workspaces', ['agent_id'], unique=False)
    op.create_index('idx_agent_workspaces_computer', 'agent_workspaces', ['computer_id'], unique=False)
    op.create_table('channels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'name')
    )
    op.create_index('idx_channels_server', 'channels', ['server_id'], unique=False)
    op.create_table('task_run_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('system_instruction', sa.Text(), nullable=False),
    sa.Column('tool_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('skill_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('memory_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('runtime_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('role_presets', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'disabled')", name='ck_task_run_templates_status'),
    sa.CheckConstraint("visibility IN ('builtin', 'server', 'user')", name='ck_task_run_templates_visibility'),
    sa.ForeignKeyConstraint(['created_by'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', name='uq_task_run_templates_slug')
    )
    op.create_index('idx_task_run_templates_status', 'task_run_templates', ['status'], unique=False)
    op.create_table('channel_members',
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_read_seq', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('channel_id', 'member_id')
    )
    op.create_table('external_routes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_selector', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('task_template_id', sa.UUID(), nullable=True),
    sa.Column('default_assignee_id', sa.UUID(), nullable=True),
    sa.Column('runtime_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('writeback_policy', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('active', 'disabled')", name='ck_external_routes_status'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['connector_id'], ['external_connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['default_assignee_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_template_id'], ['task_run_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_external_routes_channel', 'external_routes', ['channel_id'], unique=False)
    op.create_index('idx_external_routes_connector_status', 'external_routes', ['connector_id', 'status'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('short_id', sa.String(length=20), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('channel_type', sa.String(length=10), nullable=False),
    sa.Column('mentions', postgresql.ARRAY(sa.UUID()), server_default=sa.text("'{}'::uuid[]"), nullable=False),
    sa.Column('seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('seq'),
    sa.UniqueConstraint('short_id')
    )
    op.create_index('idx_messages_channel', 'messages', ['channel_id', 'created_at'], unique=False)
    op.create_index('idx_messages_parent', 'messages', ['parent_id'], unique=False, postgresql_where=sa.text('parent_id IS NOT NULL'))
    op.create_index('idx_messages_seq', 'messages', ['seq'], unique=False)
    op.create_table('saved_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('item_type', sa.String(length=20), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'item_type', 'item_id', name='uq_saved_items_account_item')
    )
    op.create_index('idx_saved_items_account', 'saved_items', ['account_id', 'created_at'], unique=False)
    op.create_index('idx_saved_items_item', 'saved_items', ['item_type', 'item_id'], unique=False)
    op.create_index('idx_saved_items_server', 'saved_items', ['server_id', 'created_at'], unique=False)
    op.create_table('server_invites',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('invited_name', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_account_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('admin', 'member')", name='ck_server_invites_role'),
    sa.ForeignKeyConstraint(['accepted_account_id'], ['accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_server_invites_server', 'server_invites', ['server_id', 'revoked_at', 'expires_at'], unique=False)
    op.create_index('idx_server_invites_token_hash', 'server_invites', ['token_hash'], unique=True)
    op.create_table('server_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('owner', 'admin', 'member')", name='ck_server_memberships_role'),
    sa.CheckConstraint("status IN ('active', 'invited', 'disabled')", name='ck_server_memberships_status'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'account_id', name='uq_server_memberships_server_account')
    )
    op.create_index('idx_server_memberships_account', 'server_memberships', ['account_id', 'status'], unique=False)
    op.create_index('idx_server_memberships_server', 'server_memberships', ['server_id', 'status'], unique=False)
    op.create_table('chat_thread_read_cursors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('root_message_id', sa.UUID(), nullable=False),
    sa.Column('last_read_seq', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_seen_message_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_seen_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['root_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chat_thread_read_cursors_member', 'chat_thread_read_cursors', ['server_id', 'member_id', 'last_read_seq'], unique=False)
    op.create_index('idx_chat_thread_read_cursors_root', 'chat_thread_read_cursors', ['root_message_id'], unique=False)
    op.create_index('uq_chat_thread_read_cursor_scope', 'chat_thread_read_cursors', ['server_id', 'member_id', 'root_message_id'], unique=True)
    op.create_table('files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_files_channel', 'files', ['channel_id', 'created_at'], unique=False)
    op.create_index('idx_files_message', 'files', ['message_id'], unique=False)
    op.create_index('idx_files_server', 'files', ['server_id', 'created_at'], unique=False)
    op.create_table('message_reactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('reaction', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('message_id', 'member_id', 'reaction')
    )
    op.create_index('idx_message_reactions_member', 'message_reactions', ['member_id'], unique=False)
    op.create_index('idx_message_reactions_message', 'message_reactions', ['message_id'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_number', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('creator_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['creator_id'], ['members.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id', 'task_number')
    )
    op.create_index('idx_tasks_assignee', 'tasks', ['assignee_id'], unique=False)
    op.create_index('idx_tasks_channel', 'tasks', ['channel_id', 'status'], unique=False)
    op.create_table('thread_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('root_message_id', sa.UUID(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requested_agent_id', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('reply_count_at_request', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('reply_count_at_summary', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('last_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summarized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_agent_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['root_message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['updated_by'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('root_message_id', name='uq_thread_summaries_root_message')
    )
    op.create_index('idx_thread_summaries_channel', 'thread_summaries', ['channel_id', 'updated_at'], unique=False)
    op.create_index('idx_thread_summaries_requested_agent', 'thread_summaries', ['requested_agent_id'], unique=False)
    op.create_index('idx_thread_summaries_server', 'thread_summaries', ['server_id', 'updated_at'], unique=False)
    op.create_table('activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_activity_agent', 'activity_logs', ['agent_id', 'occurred_at'], unique=False)
    op.create_index('idx_activity_server', 'activity_logs', ['server_id', 'occurred_at'], unique=False)
    op.create_index('idx_activity_task', 'activity_logs', ['task_id'], unique=False)
    op.create_table('event_records',
    sa.Column('seq', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('server_id', 'seq', name='uq_event_records_server_seq')
    )
    op.create_index('idx_event_records_created', 'event_records', ['server_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_event_records_message', 'event_records', ['message_id'], unique=False, postgresql_where=sa.text('message_id IS NOT NULL'))
    op.create_index('idx_event_records_server_actor_seq', 'event_records', ['server_id', 'actor_id', 'seq'], unique=False, postgresql_where=sa.text('actor_id IS NOT NULL'))
    op.create_index('idx_event_records_server_channel_seq', 'event_records', ['server_id', 'channel_id', 'seq'], unique=False, postgresql_where=sa.text('channel_id IS NOT NULL'))
    op.create_index('idx_event_records_server_seq', 'event_records', ['server_id', 'seq'], unique=False)
    op.create_index('idx_event_records_server_type_seq', 'event_records', ['server_id', 'event_type', 'seq'], unique=False)
    op.create_index('idx_event_records_task', 'event_records', ['task_id'], unique=False, postgresql_where=sa.text('task_id IS NOT NULL'))
    op.create_table('external_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_scope_type', sa.String(length=40), nullable=False),
    sa.Column('external_scope_id', sa.Text(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('thread_root_message_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("external_scope_type IN ('chat', 'thread', 'topic', 'issue', 'project')", name='ck_external_sessions_scope_type'),
    sa.CheckConstraint("status IN ('active', 'archived', 'disabled')", name='ck_external_sessions_status'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['connector_id'], ['external_connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_root_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_external_sessions_local_task', 'external_sessions', ['server_id', 'task_id'], unique=False, postgresql_where=sa.text('task_id IS NOT NULL'))
    op.create_index('uq_external_sessions_scope', 'external_sessions', ['connector_id', 'external_scope_type', 'external_scope_id'], unique=True)
    op.create_table('memory_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('entry_kind', sa.String(length=40), nullable=False),
    sa.Column('content_text', sa.Text(), nullable=True),
    sa.Column('blob_key', sa.Text(), nullable=True),
    sa.Column('file_id', sa.UUID(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), server_default=sa.text('0'), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('source_channel_id', sa.UUID(), nullable=True),
    sa.Column('source_thread_id', sa.UUID(), nullable=True),
    sa.Column('source_task_id', sa.UUID(), nullable=True),
    sa.Column('source_path', sa.Text(), nullable=True),
    sa.Column('author_member_id', sa.UUID(), nullable=True),
    sa.Column('visibility', sa.String(length=20), server_default=sa.text("'inherited'"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("scope_type IN ('agent', 'channel', 'task', 'thread')", name='ck_memory_entries_scope_type'),
    sa.ForeignKeyConstraint(['author_member_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_thread_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_entries_scope_updated', 'memory_entries', ['server_id', 'scope_type', 'scope_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index('idx_memory_entries_source_message', 'memory_entries', ['server_id', 'source_message_id'], unique=False, postgresql_where=sa.text('source_message_id IS NOT NULL'))
    op.create_index('idx_memory_entries_source_task', 'memory_entries', ['server_id', 'source_task_id'], unique=False, postgresql_where=sa.text('source_task_id IS NOT NULL'))
    op.create_index('uq_memory_entries_scope_path_active', 'memory_entries', ['server_id', 'scope_type', 'scope_id', 'path'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('reminders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fire_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('repeat', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fired_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_reminders_agent', 'reminders', ['agent_id', 'status', 'fire_at'], unique=False)
    op.create_index('idx_reminders_server', 'reminders', ['server_id', 'status', 'fire_at'], unique=False)
    op.create_table('task_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('assignee_id', sa.UUID(), nullable=False),
    sa.Column('assignee_type', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=80), nullable=False),
    sa.Column('role_key', sa.String(length=80), nullable=True),
    sa.Column('role_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('assignment_mode', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('template_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('execution_strategy', sa.String(length=40), nullable=False),
    sa.Column('run_order', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("assignee_type IN ('member', 'agent')", name='ck_task_assignments_assignee_type'),
    sa.CheckConstraint("assignment_mode IN ('leader_designated', 'direct_drag', 'agent_delegated', 'system', 'task_created', 'external_feishu')", name='ck_task_assignments_mode'),
    sa.CheckConstraint("status IN ('active', 'completed', 'cancelled')", name='ck_task_assignments_status'),
    sa.ForeignKeyConstraint(['assignee_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['task_run_templates.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_assignments_assignee', 'task_assignments', ['assignee_id', 'status'], unique=False)
    op.create_index('idx_task_assignments_task', 'task_assignments', ['task_id'], unique=False)
    op.create_table('memory_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.Column('scope_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.Text(), nullable=False),
    sa.Column('base_entry_id', sa.UUID(), nullable=True),
    sa.Column('base_sha256', sa.String(length=64), nullable=True),
    sa.Column('proposed_content_text', sa.Text(), nullable=True),
    sa.Column('proposed_blob_key', sa.Text(), nullable=True),
    sa.Column('author_member_id', sa.UUID(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'open'"), nullable=False),
    sa.Column('reviewer_member_id', sa.UUID(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("scope_type IN ('agent', 'channel', 'task', 'thread')", name='ck_memory_proposals_scope_type'),
    sa.CheckConstraint("status IN ('open', 'accepted', 'rejected', 'superseded')", name='ck_memory_proposals_status'),
    sa.ForeignKeyConstraint(['author_member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['base_entry_id'], ['memory_entries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewer_member_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_memory_proposals_scope_status', 'memory_proposals', ['server_id', 'scope_type', 'scope_id', 'status', sa.literal_column('updated_at DESC')], unique=False)
    op.create_table('task_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('assignment_id', sa.UUID(), nullable=True),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('channel_id', sa.UUID(), nullable=False),
    sa.Column('source_message_id', sa.UUID(), nullable=True),
    sa.Column('thread_root_message_id', sa.UUID(), nullable=True),
    sa.Column('parent_run_id', sa.UUID(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('template_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('role_key', sa.String(length=80), nullable=True),
    sa.Column('role_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('attempt', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('trigger_type', sa.String(length=40), nullable=False),
    sa.Column('runtime_workspace_id', sa.UUID(), nullable=True),
    sa.Column('computer_id', sa.UUID(), nullable=True),
    sa.Column('daemon_id', sa.String(length=80), nullable=True),
    sa.Column('runtime', sa.String(length=40), nullable=True),
    sa.Column('runtime_provider', sa.String(length=80), nullable=True),
    sa.Column('runtime_model', sa.String(length=120), nullable=True),
    sa.Column('prompt_profile', sa.String(length=80), nullable=False),
    sa.Column('workspace_session_id', sa.String(length=255), nullable=True),
    sa.Column('runtime_session_id', sa.String(length=255), nullable=True),
    sa.Column('context_session_id', sa.String(length=255), nullable=False),
    sa.Column('cwd', sa.Text(), nullable=True),
    sa.Column('context_scope', sa.String(length=20), nullable=False),
    sa.Column('context_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('context_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_usage', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_usage_summary', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('completion_policy', sa.String(length=40), nullable=False),
    sa.Column('output_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output_message_id', sa.UUID(), nullable=True),
    sa.Column('failure_code', sa.String(length=80), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("context_scope IN ('channel', 'thread', 'task', 'run')", name='ck_task_runs_context_scope'),
    sa.CheckConstraint("status IN ('queued', 'dispatched', 'running', 'awaiting_input', 'completed', 'failed', 'cancelled')", name='ck_task_runs_status'),
    sa.ForeignKeyConstraint(['agent_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['assignment_id'], ['task_assignments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['computer_id'], ['computers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['output_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['parent_run_id'], ['task_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['runtime_workspace_id'], ['agent_workspaces.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['task_run_templates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['thread_root_message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_runs_agent', 'task_runs', ['agent_id', 'status'], unique=False)
    op.create_index('idx_task_runs_assignment', 'task_runs', ['assignment_id'], unique=False)
    op.create_index('idx_task_runs_task', 'task_runs', ['task_id', 'created_at'], unique=False)
    op.create_index('idx_task_runs_workspace', 'task_runs', ['runtime_workspace_id'], unique=False)
    op.create_table('external_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('connector_id', sa.UUID(), nullable=False),
    sa.Column('route_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('source_event_id', sa.Text(), nullable=True),
    sa.Column('source_message_id', sa.Text(), nullable=True),
    sa.Column('source_thread_id', sa.Text(), nullable=True),
    sa.Column('dedup_key', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('actor_external_id', sa.Text(), nullable=True),
    sa.Column('normalized', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw_ref', sa.Text(), nullable=True),
    sa.Column('channel_id', sa.UUID(), nullable=True),
    sa.Column('message_id', sa.UUID(), nullable=True),
    sa.Column('task_id', sa.UUID(), nullable=True),
    sa.Column('task_run_id', sa.UUID(), nullable=True),
    sa.Column('failure_code', sa.String(length=80), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('received', 'accepted', 'dropped', 'failed', 'completed', 'writeback_failed')", name='ck_external_events_status'),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['connector_id'], ['external_connectors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_id'], ['external_routes.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['external_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_run_id'], ['task_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_external_events_server_created', 'external_events', ['server_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_external_events_status', 'external_events', ['server_id', 'status'], unique=False)
    op.create_index('idx_external_events_task_run', 'external_events', ['task_run_id'], unique=False, postgresql_where=sa.text('task_run_id IS NOT NULL'))
    op.create_index('uq_external_events_connector_dedup', 'external_events', ['connector_id', 'dedup_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_external_events_connector_dedup', table_name='external_events')
    op.drop_index('idx_external_events_task_run', table_name='external_events', postgresql_where=sa.text('task_run_id IS NOT NULL'))
    op.drop_index('idx_external_events_status', table_name='external_events')
    op.drop_index('idx_external_events_server_created', table_name='external_events')
    op.drop_table('external_events')
    op.drop_index('idx_task_runs_workspace', table_name='task_runs')
    op.drop_index('idx_task_runs_task', table_name='task_runs')
    op.drop_index('idx_task_runs_assignment', table_name='task_runs')
    op.drop_index('idx_task_runs_agent', table_name='task_runs')
    op.drop_table('task_runs')
    op.drop_index('idx_memory_proposals_scope_status', table_name='memory_proposals')
    op.drop_table('memory_proposals')
    op.drop_index('idx_task_assignments_task', table_name='task_assignments')
    op.drop_index('idx_task_assignments_assignee', table_name='task_assignments')
    op.drop_table('task_assignments')
    op.drop_index('idx_reminders_server', table_name='reminders')
    op.drop_index('idx_reminders_agent', table_name='reminders')
    op.drop_table('reminders')
    op.drop_index('uq_memory_entries_scope_path_active', table_name='memory_entries', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index('idx_memory_entries_source_task', table_name='memory_entries', postgresql_where=sa.text('source_task_id IS NOT NULL'))
    op.drop_index('idx_memory_entries_source_message', table_name='memory_entries', postgresql_where=sa.text('source_message_id IS NOT NULL'))
    op.drop_index('idx_memory_entries_scope_updated', table_name='memory_entries')
    op.drop_table('memory_entries')
    op.drop_index('uq_external_sessions_scope', table_name='external_sessions')
    op.drop_index('idx_external_sessions_local_task', table_name='external_sessions', postgresql_where=sa.text('task_id IS NOT NULL'))
    op.drop_table('external_sessions')
    op.drop_index('idx_event_records_task', table_name='event_records', postgresql_where=sa.text('task_id IS NOT NULL'))
    op.drop_index('idx_event_records_server_type_seq', table_name='event_records')
    op.drop_index('idx_event_records_server_seq', table_name='event_records')
    op.drop_index('idx_event_records_server_channel_seq', table_name='event_records', postgresql_where=sa.text('channel_id IS NOT NULL'))
    op.drop_index('idx_event_records_server_actor_seq', table_name='event_records', postgresql_where=sa.text('actor_id IS NOT NULL'))
    op.drop_index('idx_event_records_message', table_name='event_records', postgresql_where=sa.text('message_id IS NOT NULL'))
    op.drop_index('idx_event_records_created', table_name='event_records')
    op.drop_table('event_records')
    op.drop_index('idx_activity_task', table_name='activity_logs')
    op.drop_index('idx_activity_server', table_name='activity_logs')
    op.drop_index('idx_activity_agent', table_name='activity_logs')
    op.drop_table('activity_logs')
    op.drop_index('idx_thread_summaries_server', table_name='thread_summaries')
    op.drop_index('idx_thread_summaries_requested_agent', table_name='thread_summaries')
    op.drop_index('idx_thread_summaries_channel', table_name='thread_summaries')
    op.drop_table('thread_summaries')
    op.drop_index('idx_tasks_channel', table_name='tasks')
    op.drop_index('idx_tasks_assignee', table_name='tasks')
    op.drop_table('tasks')
    op.drop_index('idx_message_reactions_message', table_name='message_reactions')
    op.drop_index('idx_message_reactions_member', table_name='message_reactions')
    op.drop_table('message_reactions')
    op.drop_index('idx_files_server', table_name='files')
    op.drop_index('idx_files_message', table_name='files')
    op.drop_index('idx_files_channel', table_name='files')
    op.drop_table('files')
    op.drop_index('uq_chat_thread_read_cursor_scope', table_name='chat_thread_read_cursors')
    op.drop_index('idx_chat_thread_read_cursors_root', table_name='chat_thread_read_cursors')
    op.drop_index('idx_chat_thread_read_cursors_member', table_name='chat_thread_read_cursors')
    op.drop_table('chat_thread_read_cursors')
    op.drop_index('idx_server_memberships_server', table_name='server_memberships')
    op.drop_index('idx_server_memberships_account', table_name='server_memberships')
    op.drop_table('server_memberships')
    op.drop_index('idx_server_invites_token_hash', table_name='server_invites')
    op.drop_index('idx_server_invites_server', table_name='server_invites')
    op.drop_table('server_invites')
    op.drop_index('idx_saved_items_server', table_name='saved_items')
    op.drop_index('idx_saved_items_item', table_name='saved_items')
    op.drop_index('idx_saved_items_account', table_name='saved_items')
    op.drop_table('saved_items')
    op.drop_index('idx_messages_seq', table_name='messages')
    op.drop_index('idx_messages_parent', table_name='messages', postgresql_where=sa.text('parent_id IS NOT NULL'))
    op.drop_index('idx_messages_channel', table_name='messages')
    op.drop_table('messages')
    op.drop_index('idx_external_routes_connector_status', table_name='external_routes')
    op.drop_index('idx_external_routes_channel', table_name='external_routes')
    op.drop_table('external_routes')
    op.drop_table('channel_members')
    op.drop_index('idx_task_run_templates_status', table_name='task_run_templates')
    op.drop_table('task_run_templates')
    op.drop_index('idx_channels_server', table_name='channels')
    op.drop_table('channels')
    op.drop_index('idx_agent_workspaces_computer', table_name='agent_workspaces')
    op.drop_index('idx_agent_workspaces_agent', table_name='agent_workspaces')
    op.drop_table('agent_workspaces')
    op.drop_index('idx_accounts_member', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('idx_members_server', table_name='members')
    op.drop_index('idx_members_computer', table_name='members')
    op.drop_table('members')
    op.drop_index('uq_external_mappings_pair', table_name='external_mappings')
    op.drop_index('idx_external_mappings_local', table_name='external_mappings')
    op.drop_index('idx_external_mappings_external', table_name='external_mappings')
    op.drop_table('external_mappings')
    op.drop_index('idx_external_connectors_server_provider', table_name='external_connectors')
    op.drop_table('external_connectors')
    op.drop_index('idx_connect_tickets_server', table_name='connect_tickets')
    op.drop_index('idx_connect_tickets_prefix', table_name='connect_tickets')
    op.drop_table('connect_tickets')
    op.drop_index('uq_computers_server_machine', table_name='computers', postgresql_where=sa.text('machine_id IS NOT NULL'))
    op.drop_index('idx_computers_server_machine', table_name='computers')
    op.drop_index('idx_computers_server', table_name='computers')
    op.drop_table('computers')
    op.drop_index('idx_api_keys_prefix', table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('servers')
    # ### end Alembic commands ###
