"""messages_seq_identity

Revision ID: 0002_messages_seq
Revises: 77b8b147f689
Create Date: 2026-07-19 13:43:26

Converts ``messages.seq`` from a plain ``BIGINT NOT NULL`` (no generator) into a
real PostgreSQL identity column.

Background (see plan 004 / unblocks plan 003-seq):
- The SQLAlchemy model historically declared ``seq`` with ``autoincrement=True``,
  but since the PK is ``id UUID``, ``autoincrement`` is a no-op and ``seq`` was
  just ``BIGINT NOT NULL`` with no sequence/identity.
- The application worked around this by assigning ``seq = max(seq) + 1`` in Python
  (``routers/public_api.py``, ``routers/agent_api.py``, ``services/reminder_scheduler.py``).
  That is a read-modify-write race.
- This migration makes ``seq`` a real DB identity so plan 003-seq can later drop
  the manual assignment.

We use ``GENERATED BY DEFAULT AS IDENTITY`` (not ``ALWAYS``): ``BY DEFAULT`` still
allows explicit ``seq=`` inserts during the transition window before plan 003-seq
removes them. ``ALWAYS`` would reject those inserts and break message posting until
plan 003-seq lands.
"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '0002_messages_seq'
down_revision: Union[str, Sequence[str], None] = '77b8b147f689'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Convert messages.seq to GENERATED BY DEFAULT AS IDENTITY."""
    # Defensive backfill: identity columns require NOT NULL and existing rows
    # need concrete values. The app always assigned seq manually, so NULLs
    # should not exist — but if any do, assign a value greater than the current
    # max, ordered by created_at for determinism.
    #
    # Implemented as UPDATE-FROM-CTE because window functions (ROW_NUMBER())
    # are not allowed directly in UPDATE's SET clause in PostgreSQL; we compute
    # them in a CTE first and join.
    op.execute("""
        WITH ranked AS (
            SELECT id, ROW_NUMBER() OVER (ORDER BY created_at) AS rn
            FROM messages
            WHERE seq IS NULL
        ), next_seq AS (
            SELECT COALESCE(MAX(seq), 0) AS m FROM messages
        )
        UPDATE messages AS tgt
        SET seq = (SELECT m FROM next_seq) + ranked.rn
        FROM ranked
        WHERE tgt.id = ranked.id;
    """)
    # Convert the existing column into an identity column. The empty parens
    # make Postgres pick a default sequence name and default start/increment
    # (both 1). BY DEFAULT permits explicit overrides during the transition.
    op.execute(
        "ALTER TABLE messages ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY;"
    )


def downgrade() -> None:
    """Revert messages.seq to a plain BIGINT NOT NULL."""
    # NOTE: the Postgres syntax is `DROP IDENTITY`, not `DROP GENERATED`.
    op.execute("ALTER TABLE messages ALTER COLUMN seq DROP IDENTITY;")
