"""finish the messages.seq transition to automatic-only allocation

Revision ID: 0003_messages_seq_auto
Revises: 0002_messages_seq
Create Date: 2026-07-23

``0002`` deliberately used ``GENERATED BY DEFAULT`` so an older application
could continue sending explicit values during the transition.  This final
barrier reconciles any such committed values and switches the column to
``GENERATED ALWAYS`` immediately before automatic-only application writers are
released.
"""

from typing import Sequence, Union

from alembic import op


revision: str = "0003_messages_seq_auto"
down_revision: Union[str, Sequence[str], None] = "0002_messages_seq"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Reconcile transition writes and reject future explicit seq values."""

    # ALTER TABLE holds an ACCESS EXCLUSIVE lock through the migration
    # transaction.  Changing the generation mode first closes the explicit-write
    # window; setval then observes every value committed before that lock.
    op.execute(
        "ALTER TABLE messages ALTER COLUMN seq SET GENERATED ALWAYS;"
    )
    op.execute("""
        SELECT setval(
            pg_get_serial_sequence('messages', 'seq'),
            COALESCE(MAX(seq), 1),
            MAX(seq) IS NOT NULL
        )
        FROM messages;
    """)


def downgrade() -> None:
    """Re-open explicit transition writes without lowering the sequence."""

    op.execute(
        "ALTER TABLE messages ALTER COLUMN seq SET GENERATED BY DEFAULT;"
    )
