/* Trellis Dashboard 演示数据（?demo 模式）。结构与 /api/dashboard 快照一致。 */
"use strict";

window.DEMO_SNAPSHOT = {
  schema: "trellis.dashboard.v1",
  generatedAt: "2026-08-18T08:00:00Z",
  project: {
    root: "/demo/smallkhoj",
    name: "smallkhoj",
    git: {
      isRepo: true,
      branch: "main",
      head: "a1b2c3d",
      dirtyFiles: [" M frontend/app/chat/page.tsx", "?? tools/trellis-dashboard/"],
      recentCommits: [
        "a1b2c3d feat(dashboard): 演示提交 1",
        "e4f5g6h fix(chat): 演示提交 2",
        "i7j8k9l chore: record journal",
      ],
    },
  },
  developer: "demo-dev",
  summary: {
    activeTasks: 3,
    byStatus: { planning: 1, in_progress: 1, completed: 1 },
    priority: { P0: 1, P1: 1, P2: 1, P3: 0 },
    archivedTotal: 12,
    dirtyFiles: 2,
    activeSessions: 2,
  },
  tasks: {
    active: [
      {
        dir: "08-18-demo-parent-task",
        title: "演示：多交付物父任务",
        description: "这是一个演示任务。**加粗**、`行内代码` 与列表：\n\n- 需求一\n- 需求二\n\n| 验收项 | 状态 |\n|---|---|\n| A | 待做 |\n| B | 待做 |",
        notes: "",
        status: "planning",
        priority: "P0",
        creator: "demo-dev",
        assignee: "demo-dev",
        createdAt: "2026-08-18",
        completedAt: null,
        branch: null,
        baseBranch: "main",
        worktreePath: null,
        commit: null,
        prUrl: null,
        scope: null,
        package: null,
        parent: null,
        children: [
          { dir: "08-18-demo-child-a", status: "in_progress", archived: false, done: false },
          { dir: "08-17-demo-done", status: null, archived: true, done: true },
        ],
        childrenProgress: { done: 1, total: 2 },
        artifacts: {
          prd: true, design: false, implement: false,
          researchFiles: ["research.md"],
          extras: ["verify-handoff.md"],
          extraDirs: [{ name: "evidence", fileCount: 2, files: ["evidence/a.json", "evidence/b.json"] }],
          implementContext: { exists: true, curated: 1, seedOnly: false, invalidLines: 0 },
          checkContext: { exists: true, curated: 0, seedOnly: true, invalidLines: 0 },
        },
        readiness: { prd: true, design: false, implement: false, contextCurated: false },
        phase: "plan",
        nextStep: "为 implement.jsonl / check.jsonl 各补充至少一条真实条目，然后 task.py start",
        risks: ["CONTEXT_NOT_CURATED"],
        meta: null,
      },
      {
        dir: "08-18-demo-child-a",
        title: "演示：进行中的子任务",
        description: "子任务示例，正在实现阶段。",
        notes: "",
        status: "in_progress",
        priority: "P1",
        creator: "demo-dev",
        assignee: "demo-dev",
        createdAt: "2026-08-18",
        completedAt: null,
        branch: "feat/demo-child",
        baseBranch: "main",
        worktreePath: "/tmp/smallkhoj-demo-child",
        commit: null,
        prUrl: null,
        scope: null,
        package: null,
        parent: "08-18-demo-parent-task",
        children: [],
        childrenProgress: null,
        artifacts: {
          prd: true, design: true, implement: true,
          researchFiles: [],
          extras: [],
          extraDirs: [],
          implementContext: { exists: true, curated: 3, seedOnly: false, invalidLines: 0 },
          checkContext: { exists: true, curated: 2, seedOnly: false, invalidLines: 0 },
        },
        readiness: { prd: true, design: true, implement: true, contextCurated: true },
        phase: "execute_finish",
        nextStep: "trellis-implement → trellis-check → trellis-update-spec → 提交 → /trellis:finish-work",
        risks: [],
        meta: null,
      },
      {
        dir: "08-17-demo-missing-prd",
        title: "演示：缺 PRD 的规划任务",
        description: "",
        notes: "",
        status: "planning",
        priority: "P2",
        creator: "demo-dev",
        assignee: "demo-dev",
        createdAt: "2026-08-17",
        completedAt: null,
        branch: null,
        baseBranch: "main",
        worktreePath: null,
        commit: null,
        prUrl: null,
        scope: null,
        package: null,
        parent: null,
        children: [],
        childrenProgress: null,
        artifacts: {
          prd: false, design: false, implement: false,
          researchFiles: [], extras: [], extraDirs: [],
          implementContext: { exists: true, curated: 0, seedOnly: true, invalidLines: 0 },
          checkContext: { exists: true, curated: 0, seedOnly: true, invalidLines: 0 },
        },
        readiness: { prd: false, design: false, implement: false, contextCurated: false },
        phase: "plan",
        nextStep: "补齐 prd.md（复杂任务还需 design.md + implement.md）",
        risks: ["MISSING_PRD", "CONTEXT_NOT_CURATED"],
        meta: null,
      },
    ],
    archivedRecent: [
      {
        dir: "08-17-demo-done",
        ref: "archive/2026-08/08-17-demo-done",
        title: "演示：已归档任务",
        status: "completed",
        priority: "P2",
        assignee: "demo-dev",
        createdAt: "2026-08-16",
        completedAt: "2026-08-17",
        month: "2026-08",
        branch: null,
        commit: "e4f5g6h",
        childCount: 0,
      },
    ],
  },
  sessions: [
    {
      key: "codex_demo-uuid-1",
      platform: "codex",
      lastSeenAt: "2026-08-18T07:40:00Z",
      currentTask: ".trellis/tasks/08-18-demo-child-a",
      staleTask: false,
    },
    {
      key: "claude_demo-uuid-2",
      platform: "claude",
      lastSeenAt: "2026-08-10T02:00:00Z",
      currentTask: ".trellis/tasks/06-01-gone-task",
      staleTask: true,
    },
  ],
  journal: {
    developer: "demo-dev",
    developers: [
      { name: "demo-dev", activeFile: "journal-1.md", totalSessions: 2, lastActive: "2026-08-18" },
    ],
    journalFiles: [{ file: "journal-1.md", lines: 1750, nearLimit: true }],
    recent: [
      { n: 2, date: "2026-08-18", title: "演示会话：仪表盘开发", commits: ["a1b2c3d"], branch: "main" },
      { n: 1, date: "2026-08-17", title: "演示会话：归档任务", commits: ["e4f5g6h", "i7j8k9l"], branch: "main" },
    ],
  },
  spec: { mode: "single-repo", specLayers: ["backend", "frontend"] },
};
